server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.22.5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false